# -*- coding: utf-8 -*-
"""L1_L2_datasummary

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-CfUEWJFJWBJC3oKEj16q1po4yh45Mac
"""

from google.colab import drive
drive.mount('/content/drive')

import os
#print(os.listdir("drive/MyDrive/"))
file_path = "drive/MyDrive/10k_sampled_L0_l2_wSoftware.csv"
import pandas as pd
import json

# Load data from CSV in Google Drive
df = pd.read_csv(file_path)

# Group by L0_pmcid and aggregate values
grouped = df.groupby('L0_pmcid').agg({
    'L0_domain': 'first',
    'L0_sw_count': 'first',
    'L0_sw_id': lambda x: list(x),
    'L1_domain': lambda x: list(x),
    'L1_pmcid': lambda x: list(x),
    'L1_sw_count': 'sum',
    'L1_sw_id': lambda x: list(x)
}).reset_index()

grouped['L1_L0_software_all'] = grouped.apply(lambda x: list(set(x['L0_sw_id'] + x['L1_sw_id'])), axis=1)

grouped.sample(10)

import math
grouped["L1_pmcid"] = [list(set(i)) for i in grouped["L1_pmcid"]]
grouped["L1_total_ref_count"] = [len(i) for i in grouped["L1_pmcid"]]

grouped["L1_sw_id"] = [list(set(i)) for i in grouped["L1_sw_id"]]
grouped['L1_sw_id'] = grouped['L1_sw_id'].apply(lambda x: [i for i in x if not math.isnan(i)])
grouped["L1_sw_count"] = [len(i) for i in grouped['L1_sw_id']]

grouped["L1_L0_sw_id"] = [list(set(i)) for i in grouped["L1_L0_software_all"]]

grouped['L1_L0_sw_id'] = grouped['L1_L0_sw_id'].apply(lambda x: [i for i in x if not math.isnan(i)])
grouped["L1_L0_sw_count"] = [len(i) for i in grouped['L1_L0_sw_id']]

grouped.to_json("drive/MyDrive/10k_sample_L1_L2_analysis.json", orient='records', lines=True)
grouped.to_csv("drive/MyDrive/10k_sample_L1_L2_analysis.csv", index=False)

grouped